### PR TITLE
Delete unused files

### PR DESCRIPTION
**Pull request by mbuchoff**
Most of this has been moved into the [project](https://github.com/users/snohio/projects/4), which I like better.

Should we delete leanbeer.md also?

### CODE REVIEW

**Comment by snohio** [comment]
Can we just have an Archive folder for reference? I get these are in other places, but for search / reference material, I'll likely come back to them.

**Comment by mbuchoff** [comment]
I'm fine with an archive folder, but isn't that what version control is for?

**Comment by snohio** [comment]
The summer 23 one is our meeting notes from our first meeting. The strategic theme is more of an over-arching theme of our group. Goals, I guess I can do away with those as they did start to get put into the Milestones. That was (mostly) AI generated.

**Review by snohio — CHANGES_REQUESTED** [review]
Would you mind putting them into an archive/ folder?  I understand that github has a history, but I often pull down and use main to search things on my local machine.

**Comment by mbuchoff** [comment]
All set. Files are archived instead of deleted.

**Review by snohio — APPROVED** [review]
GTG
:shipit:

**Pull request merged**
